### ISSUE TITLE
Extra <li> in nav template on front page

### ISSUE THREAD

**Issue by jsbean** [dn-m/dn-m.github.io#14]
It looks like we have inserted an extra `<li>` in the nav bar on the front page. 

Is this generated in [`GenerateFrontpage.sh`](https://github.com/dn-m/dn-m.github.io/blob/master/GenerateFrontpage.sh), for a `misc` section? : 

``` html
<li class="nav-group-name">
    <ul class="nav-group-tasks">
    </ul>
</li>
```

**Comment by jsbean** [comment]
Ahh, it's in [index.mo](https://github.com/dn-m/dn-m.github.io/blob/master/index.mo):

``` html
<li class="nav-group-name">
    <ul class="nav-group-tasks">
        {{#MISC}}
        <li class="nav-group-task">
            <a class="nav-group-task-link" href="{{.}}/index.html">{{.}}</a>
        </li>
        {{/MISC}}
    </ul>
</li>
```

**Comment by jsbean** [comment]
Maybe we hold out on injecting that until we've got `misc` stuff.

**Comment by delucis** [comment]
So it turns out that mustache is spectacularly basic. It handles arrays by declaring:

```
{{#MISC}}
    Loop stuff in here.
    Current item in array: {{.}}
    If $MISC undeclared, none of this shows up.
{{/MISC}}`
```

But it is [proudly logic-less](http://mustache.github.io/), so there’s no way to check if `$MISC` exists, render out the wrapper if it does, and then iterate through the array within that.

I went for this slightly buggy version, because currently `GenerateFrontpage.sh` relies on pre-declared arrays of your `Utility` and `MusicModel` groupings, just stripping out members of those arrays if there’s no corresponding subdirectory. I thought it would be desirable to display new subdirectories automatically (as `Misc`), if nothing else so as to flag their need for categorisation.

If there’s a way to collect that categorisation (Utility, MusicModel, etc.) programmatically, that would be better.

**Comment by delucis** [comment]
We can do logic at the bash level obviously, so one option would be to test for `$MISC` size in `GenerateFrontpage.sh`, and call different templates depending on the response.
