### ISSUE TITLE
Generate installation instructions for each framework

### ISSUE THREAD

**Issue by jsbean** [dn-m/dn-m.github.io#32]
Create a script that generates

``` Markdown
<a name="integration"></a>
## Integration

### Carthage
Integrate **$FRAMEWORKNAME** into your OSX or iOS project with [Carthage](https://github.com/Carthage/Carthage).

1. Follow [these instructions](https://github.com/Carthage/Carthage#installing-carthage) to install Carthage, if necessary.
2. Add `github "dn-m/$FRAMEWORKNAME"` to your [Cartfile](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile) 
3. Follow [these instructions](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) to integrate **$FRAMEWORKNAME** into your OSX or iOS project.
```

and inserts it to the beginning of the appropriate `README.md` file.

**Comment by delucis** [comment]
Do you mean the `README.md` in each framework’s repository? Is Jazzy generating the rest of `README.md` or are they all written manually at the moment?

**Comment by jsbean** [comment]
Yes, the `README.md` in each framework's repository.

Currently, the `README.md` files are written manually. Though the `README.md` files are parsed to be injected into the `index.html` of the respective site.

**Comment by jsbean** [comment]
Included in #34.

**Comment by delucis** [comment]
Ok, I’ll think about this — week just heated up when I realised the stuff I have to do for next week.

Also, what did you do to GitHub?

![image](https://cloud.githubusercontent.com/assets/357379/13802167/5ddbcc86-eb0f-11e5-93eb-409e3d4a14cc.png)

**Comment by delucis** [comment]
(You can assign this to me if you like. I can’t seem to do that myself?)

**Comment by jsbean** [comment]
⚡️🔥💥

**Comment by delucis** [comment]
:thought_balloon: Hmm, similarly to your Xcode question, this kind of doesn’t totally belong here.

Although the `README.md` of a Framework is being pulled into Jazzy as the front page of that Framework’s docs, generating the actual `README.md` should fall under build responsibilities of the Framework repo itself.

Of course, the code can be abstracted out across all repos. Might it make sense — perhaps in tandem with your Xcode set-up investigations — to create some kind of `dn-mMatriarch` whose role it is to manage shared utilities and defaults? The difficulty handling those seems the biggest problem with the otherwise very clean modularity right now.

**Comment by jsbean** [comment]
Yes. Totally. Can't work on this for the next couple days, but this will be the next todo.

Are you thinking a new repo for this?

I would like to keep the `DocumentationTools` (what this might become) and `Xcodeproj` separate, as they do have different concerns, and scope (in terms of user base).

Thoughts?

**Comment by jsbean** [comment]
Migrated to [DocumentationTools](https://github.com/dn-m/DocumentationTools/issues).
