### ISSUE TITLE
Make `code` header doc text smaller

### ISSUE THREAD

**Issue by jsbean** [dn-m/dn-m.github.io#36]
Too big:

> <img width="768" alt="screen shot 2016-03-17 at 7 43 03 pm" src="https://cloud.githubusercontent.com/assets/7040073/13864534/826bf534-ec78-11e5-8e7c-2593a2a79b9e.png">

**Comment by delucis** [comment]
[This](https://dn-m.github.io/Duration/Structs/MetricalDurationInterval.html#/s:FV8Duration24MetricalDurationInterval4trimFS0_FT4stopVS_16MetricalDuration_GSqS0__) depends a lot on which font is actually being used by a viewer’s browser, so I’d sound a note of caution (especially because the Jazzy styling mostly seems pretty exquisitely balanced to me).

The font stack currently looks like this:

``` css
code {
    font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace
}
```

which means you see the first font in that list that is installed on your system.

In both our cases that looks to be `Menlo`. However other systems may differ. `Courier` in particular has a much smaller footprint, which wouldn’t look so great smaller.

**Comment by jsbean** [comment]
Noted. Agreed about the default styling being exquisite :).

We shall leave it be.
